### ISSUE TITLE
onSnapToItem receives incorrect parameter

### ISSUE THREAD

**Issue by piuccio** [archriss/react-native-snap-carousel#105]
I'm using this code

```js
<View>
  <Carousel
    ref={(carousel) => { this.carousel = carousel; }}
    sliderWidth={pageWidth}
    itemWidth={pageWidth}
    inactiveSlideScale={1}
    slideStyle={{ width: pageWidth }}
    onSnapToItem={(index) => console.log(index)}
  >
    <View></View>
    <View></View>
    <View></View>
    <View></View>
  </Carousel>
  <Button onPress={() => this.carousel.snapToItem(4)}>Last</Button>
</View>
```

There's a button that should snap to the last item. It works fine when you are displaying any of the carousel pages, however it fails if you're on the first item and swipe left.

Steps:

1. When the page load you're seeing the first item
1. Swipe left, nothing will change because it's the first item
1. Click on the button
1. `onSnapToItem` gets called with `index = 1` instead of `index = 4`

The View that gets rendered is actually the 4th one, so the only thing wrong is the index received by the callback

**Comment by piuccio** [comment]
Forgot to mention that I'm using the version `2.4.0` on react native `0.45.1`

**Comment by bd-arc** [comment]
Hi @piuccio,

Thanks for letting me know. I'll investigate.

Note that callback handling is a real mess since `ScrollView` doesn't provide any callback when scroll ends; so I'm not surprised that some fine-tuning still needs to be done.

However, would you mind testing with the [`flatlist` branch](https://github.com/archriss/react-native-snap-carousel/tree/flatlist)? It contains a lot of updates and a new implementation that might help with the issue. There is a [migration guide](https://github.com/archriss/react-native-snap-carousel/tree/flatlist#migration-from-version-2x) in the README, and it is pretty straightforward.

**Comment by bd-arc** [comment]
Hey @piuccio,

I've fixed the issue (see [this commit](https://github.com/archriss/react-native-snap-carousel/commit/9af3ac4d61e42f1668bc3c09acc790a1f8ac74d6)).

Thank you for discovering this very specific matter! Note that the fix is only available in the `flatlist` branch for now.

**Comment by adarshTS** [comment]
Can someone help with this [https://stackoverflow.com/questions/45992749/how-to-get-and-pass-the-details-of-the-active-slide-in-react-native-using-react](https://stackoverflow.com/questions/45992749/how-to-get-and-pass-the-details-of-the-active-slide-in-react-native-using-react)
