### ISSUE TITLE
Android. Debug build do not work as production build

### ISSUE THREAD

**Issue by xvonabur** [archriss/react-native-snap-carousel#110]
Hello.

I've run into the issue where android debug build is working not the same as production build. 
I made a simple app which shows only one carousel item at the time. Production build works fine. But debug with enabled/disabled remote debugging is working like this:

![gif](https://thumbs.gfycat.com/ThoroughEvergreenIberianlynx-size_restricted.gif)

So, basically, I can move through all items in once during the first slide gesture (unexpected). But after that, I can slide only one item per sliding gesture (expected behaviour).

My code is simple:

```javascript
<Carousel
  animationOptions={{
    easing: Easing.out(Easing.quad),
    duration: 350,
    isInteraction: false,
    useNativeDriver: true
  }}
  sliderWidth={Metrics.screenWidth}
  itemWidth={Metrics.screenWidth}
  inactiveSlideScale={1}
  inactiveSlideOpacity={1}
  slideStyle={styles.slide}
  decelerationRate={'fast'}
  swipeThreshold={5}
  scrollEndDragDebounceValue={10}
  onSnapToItem={ (index) => { this.setState({ currentStep: index }) } }
  ref={(carousel) => { this._carousel = carousel }}>
  {
    this.state.stepsData.map((step, index) => {
      return <StepInfo key={index} data={step} />
    })
  }
</Carousel>
```

I saw #34, but I would like to know whether I can do with my code to fix this behaviour. Am I missing something?

**Comment by bd-arc** [comment]
Hi @xvonabur,

`ScrollView`'s performance on Android while debugging is everything but ideal. Unfortunately there is nothing we can do about it since React Native [doesn't offer a proper scroll callback for its component](https://github.com/archriss/react-native-snap-carousel#scrollviews-limitations). This means that when momentum is disabled (the default behavior), we have to rely on `onScrollEndDrag` and a bunch of hacks to make it work. In debug mode, `onScrollEndDrag` is apparently triggered a bit late, just enough to let you scroll through multiple slides...

Still, here are a few things you could try:

- disabling `JS Dev Mode` in [the dev menu](https://stackoverflow.com/questions/29289304/how-do-you-debug-react-native), which usually result in a huge performance boost on Android
- setting `scrollEndDragDebounceValue` to `0` for your debug build
- setting `enableMomentum` to `true` for your debug build so that the callback will be triggered on `onMomentumScrollEnd` instead of `onScrollEndDrag`. Note that you **will** be able to scroll through multiple slides, but the callback might be more reliable.

Let me know if any of this helped!

**Comment by xvonabur** [comment]
Thanks, @br-arc.

I've already tried all your suggestions, but unfortunately neither of them suits me. It's not a big deal for me, cause production build is fine. I will use it for testing. It's really annoying to see such android only limitations, through. Hopefully some day things will be better.
