### ISSUE TITLE
Disabling scroll

### ISSUE THREAD

**Issue by fendorio** [archriss/react-native-snap-carousel#119]
Is there a way to conditionally disable scrolling the slideshow? I.e. temporarily disable scroll and have the user have to manually navigate between slides (next/prev buttons)

**Comment by bd-arc** [comment]
Hi @fendorio,

You can set prop [`scrollEnabled`](https://facebook.github.io/react-native/docs/scrollview.html#scrollenabled) to either `true` (default) or `false`. This prop is inherited from `ScrollView`.

Note that there is a side-effect with `autoplay` because `onTouchStart` is triggered even when the prop is set to `false`. I will push a fix for that shortly.
