### ISSUE TITLE
snapToPrev - vertical

### ISSUE THREAD

**Issue by NicholasBertazzon** [archriss/react-native-snap-carousel#120]
Hi,
I'm using the latest version of snap-carousel and when i press on my button that call "snapToPrev()", and i'm focussing the first item of the vertical list (yes, I'm using it in vertical mode), instead of doing nothing(since I'm already in the first item), it snaps to the last item. It seems like it counts the last item (index 10 right now in my app) as the first.

SnapToNext works perfectly :)

My carousel.
`<Carousel
vertical={true}
ref={(carousel) => {
                            this._carousel = carousel;
                        }}
                        inactiveSlideScale={1.0}
                        animationOptions={{duration:0,easing:Easing.elastic(0)}}
                        sliderWidth={windowWidth}
                        enableSnap={false}
                        sliderHeight={windowHeight / 100 * 67 / 8}
                        itemWidth={windowWidth}
                        itemHeight={windowHeight / 100 * 67 / 8}
                    >
                        {slides}
                    </Carousel>`

**Comment by bd-arc** [comment]
Hi @NicholasBertazzon,

Well, that's the expected behavior at the moment. If you look at [theses lines](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L750:L752), you'll understand why.

Let's face it: it's a pretty bad substitute for a proper loop mode, on which I'm currently working. When it's going to be ready, snapping from one edge to the other will be a thing of the past.

Stay tuned!

**Comment by NicholasBertazzon** [comment]
Oh, ok, thanks for the clarification.

**Comment by bd-arc** [comment]
Hi @NicholasBertazzon,

I forgot to let you know that since version `3.3.0` and the introduction of the loop feature, this should work as expected for you ;-)

**Comment by NicholasBertazzon** [comment]
Thanks @bd-arc for let me know!
