### ISSUE TITLE
cannot read property 'foreach' of undefined

### ISSUE THREAD

**Issue by EyreGe** [archriss/react-native-snap-carousel#124]
<Carousel
          sliderWidth={viewportWidth}
          itemWidth={viewportWidth}
          slideStyle={{ width: viewportWidth }}
          inactiveSlideOpacity={1}
          inactiveSlideScale={1}
        >
            <View style={{ height: viewportHeight }} /> 
            <View style={{ height: viewportHeight }} /> 
            <View style={{ height: viewportHeight }} /> 
        </Carousel>

**Comment by bendellarocco** [comment]
+1

"react-native-snap-carousel": "^3.0.0",
"react-native": "^0.44.0",

Implementation: 
`<Carousel
              ref={(carousel) => { this._carousel = carousel; }}
              sliderWidth={width}
              itemWidth={width * .9}
              >
              <View><Text>jbsfjhbfsdhjfbsdjfb</Text></View>
              <View><Text>kjasbndkjsdbnsjkdnasjkdnasjkasnjk</Text></View>
            </Carousel>`

**Comment by EyreGe** [comment]
my version "react-native": "^0.45.1"

**Comment by VrajSolanki** [comment]
Cannot add property 2, object is not extensible, react-native version:  "^0.45.1"

**Comment by bd-arc** [comment]
Hi guys,

Have you made sure to read the [migration guide](https://github.com/archriss/react-native-snap-carousel#migration-from-version-2x) as well as the [release notes](https://github.com/archriss/react-native-snap-carousel/releases/tag/v3.0.0) for version 3.0.0? 

As the version tag indicates, there were some breaking changes :-) Implementation is now based on `FlatList` instead of `ScrollView`, which changes the way to handle your slides.

**Comment by VrajSolanki** [comment]
@bd-arc hi, I may be wrong but dug in the code for Carousel.js line 781, replacing const customData = data, by let customData = [] and then pushing data in customData seems to solve the problem for me for now. I don't know what it is doing it here, or how can it be fixed. Line 780 in Carousel need to fix?

Please Suggest!

**Comment by bd-arc** [comment]
@VrajSolanki I made a mistake while publishing version `3.0.0` and ended up pushing some temporary code I forgot to stash...

Can you try version `3.1.0` and let me know if the issue persists?

**Comment by VrajSolanki** [comment]
@bd-arc Hi, i checked the commit but that does not fix the Carousel.js and that has CUSTOM_DATA check issue  console log as well, if you could just have a look or I can request a PR and check my updates?? 
Issue 129 https://github.com/archriss/react-native-snap-carousel/issues/129

**Comment by bd-arc** [comment]
@VrajSolanki You won't find a commit that fixes it because the mistake was made when publishing to `npm` (I forgot to stash some temporary code).

As you can see [in the source code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js), there is no `console.log()` call. So, trust me: delete the appropriate folder in `nodes_modules`, update to `3.1.0` and the issue will be gone ;-) You can also take a look at [this thread](https://github.com/archriss/react-native-snap-carousel/issues/125).

**Comment by VrajSolanki** [comment]
@bd-arc cool
