### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.FlatList.propTypes')

### ISSUE THREAD

**Issue by Softcadbury** [archriss/react-native-snap-carousel#126]
Hello, I got this error when using react-native-snap-carousel 3.0.0.
I use react 15.4.2 and react-native 0.42.3 (I cannot update yet).

This code seems to fix the problem :
In Carousel.js, replace `...FlatList.propTypes,` by `...FlatList ? FlatList.propTypes : {},`

**Comment by bd-arc** [comment]
Hi @Softcadbury,

Starting with version `3.0.0`, the plugin is now based on `FlatList` instead of `ScrollView`. This comes with a bunch of benefits, but also with one drawback: **since `FlatList` was introduced in React Native `0.43.x`, you are stuck with version `2.4.0` of the plugin if you're currently using an older release of RN**. Sorry about that, but there is no way for us to maintain backward compatibility...

I've added [a note in the README](https://github.com/archriss/react-native-snap-carousel/#react-native-version) so that users are warned.
