### ISSUE TITLE
When swiping through slides quickly carousel returns to item at first index

### ISSUE THREAD

**Issue by gonzalezchris** [archriss/react-native-snap-carousel#137]
I ran into an issue, where if I swipe (left) at a high speed through a few full screen slides then instead of staying on the slide I stopped sliding on, it instead returns to the first slide. 

In the attached gif I am sliding my finger to the left for several slides, and then when I let go, the carousel seems to be swiping right on its own. Any ideas?

In some cases, while swiping left, the carousel also tries to "fight" me and swipe in the opposite direction.
![ezgif-1-ed11ae3bd5](https://user-images.githubusercontent.com/4773680/30005855-b4db965a-90b9-11e7-9005-a9c83e1d17c5.gif)

Carousel Component Set up
```
            <Carousel
              ref={c => { this.carousel = c; }}
              data={this.props.moments}
              renderItem={this.renderItem}
              sliderWidth={width}
              itemWidth={width}
              containerCustomStyle={{ flex: 1 }}
              inactiveSlideScale={1}
              inactiveSlideOpacity={1}
              scrollEndDragDebounceValue={0}
              decelerationRate='fast'
              disableVirtualization={false}
              firstItem={this.props.activeIndex}
              onSnapToItem={(slideIndex) => {
                this.props.didSwipeMoment(slideIndex);
              }}
            />
```

**Comment by bd-arc** [comment]
Hi @gonzalezchris,

Since the plugin hasn't been designed with fullscreen slides in mind, some fine-tuning may be needed ;-)

One question thought: have you tried your app in production mode? Android performance is just horrendous in debug mode (see the ["Known issues"](https://github.com/archriss/react-native-snap-carousel#known-issues) section of the doc).

**Comment by bd-arc** [comment]
I would also try setting `activeSlideOffset` to a much higher value than the default one in order to prevent the "fighting effect".

Currently, when you're not triggering a short snap, you need to slide almost half the screen for the next slide to become active. It might be useful for you to temporary set `inactiveSlideScale` to something other than `1` in order to clearly see when you pass the pivot point.

**Comment by Jayiitb** [comment]
Hi @bd-arc,
Thanks for this awesome component.

Can we limit its scroll to one slide per swipe? Like the one shown in demo gif 'Archriss' "Ville d'Aix-en-Provence" app'.

Facing the same issue of swiping back/fighting with scroll.

**Comment by bd-arc** [comment]
Hi @Jayiitb,

Are you using fullscreen slides too?

I'm going to see if I can implement a specific prop that would smooth things out for this kind of use cases. Note that this is far from easy because of [miscellaneous limitations](https://github.com/archriss/react-native-snap-carousel/#flatlist-and-scrollviews-limitations).

**Comment by bd-arc** [comment]
Hi @gonzalezchris @Jayiitb,

I've just released [version `3.2.0`](https://github.com/archriss/react-native-snap-carousel/releases/tag/v3.2.0) which should help with your issue. Can you confirm? Don't forget to test [without enabling JS Dev Mode](https://github.com/archriss/react-native-snap-carousel/#android-performances).

Note that there are a lot of issues at stake with how the carousel behave on Android, but it all comes down to React Native's implementation. In the near future, I'll be working on a custom scroller/`PanResponder` implementation in order to greatly enhance carousel's behavior and "feeling".

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.

**Comment by Jayiitb** [comment]
Hi @bd-arc,
I regret not replying back on time.
Your changes have worked out of the blue. 
Thanks.

**Comment by bd-arc** [comment]
@Jayiitb No worries ;-) Thanks for letting me know!

**Comment by gonzalezchris** [comment]
@bd-arc I apologize for the delayed response, this fixed the issue, thanks a bunch!
