### ISSUE TITLE
Swipe up to remove an item

### ISSUE THREAD

**Issue by medisoft** [archriss/react-native-snap-carousel#149]
Hello. I'm looking for a component like yours, that can get a bunch of cards/elements, and the user be able to swipe left/right to browse the elements, but when the user swipes up, the card needs to be removed from the list and a new card loaded from the backend using state or something.

Also when swipe down, the card should load another scene/page.

Is this possible?

Thank you!

**Comment by bd-arc** [comment]
Hi @medisoft,

Currently, this can't be implemented because the plugin is based on a `FlatList` component while what you're after requires an advanced `PanResponder`. I've favored the former so far because of its ability to handle huge amounts of items.

Still, my roadmap includes implementing a custom `PanResponder` on top of the `FlatList` to unify the snap behavior between Android and iOS. This may also allow more advanced interactions like the ones you're after. Honestly, I won't be able to add this kind of feature anytime soon; it's going to take a lot of hard work. But it's my wish to make it happen in the long run.

For now, these plugins might be of interest to you:
- https://github.com/alexbrillant/react-native-deck-swiper
- https://github.com/meteor-factory/react-native-tinder-swipe-cards
