### ISSUE TITLE
Use onMomentumScrollEnd instead of onScrollEndDrag

### ISSUE THREAD

**Issue by FakeYou** [archriss/react-native-snap-carousel#16]
Using the option `snapOnAndroid` currently results in very bad experience where carousel snaps on the item where the drag was released. By using `onMomentumScrollEnd` instead of `onScrollEndDrag` here https://github.com/archriss/react-native-snap-carousel/blob/master/index.js#L404 the experience is made much smoother.

Example with `onScrollEndDrag`: https://gfycat.com/SmallCaringAfricanharrierhawk  
Example with `onMomentumScrollEnd`: https://gfycat.com/PhysicalFearlessBarracuda

**Comment by Exilz** [comment]
Hi @FakeYou , thanks for the suggestion. I guess we haven't noticed this since our swipers entries are usually very wide components, unlike your example, so we couldn't swipe to far away entries like you did :)

This needs to be tested on iOS and we have to check for potential drawbacks (I guess there aren't).
Maybe `onScrollEndDrag` behaves better in some cases. If so, I guess we could add a new prop for this.

**Comment by Exilz** [comment]
Thanks a lot for the suggestion, it will be added to the next release.
See https://github.com/archriss/react-native-snap-carousel/pull/20

**Comment by FakeYou** [comment]
Awesome man! Thank you for the update.
