### ISSUE TITLE
Cannot read property 'start'of undefined

### ISSUE THREAD

**Issue by kozillla** [archriss/react-native-snap-carousel#170]
Hi, 

After upgrading react-native-snap-carousel to 3.3.0, I''m running into issue with carousel initialization. In some occasions (happens only in debug mode) app crash with :   

Cannot read property 'start'of undefined
which leads to :

(Carousel.js:487:46)
...
        const offset = this._positions[index].start;
...

Ps. Just additional question , is it any way to increase momentum for Android (it can be controlled in IOS by decelerationRate but cant figure out how to "slow down" carousel in Android), by the way great package guys 

thanks,
Karol

**Comment by bd-arc** [comment]
Hi @kozillla,

I assume you're having the issue on Android only, aren't you? To be honest, Android debug mode is a real mess: timeouts regularly desynchronize, scroll events are called in a pretty random order... It's a complete developer nightmare! Still, I'm going to add a check in order to prevent the issue you're currently facing.

Regarding your other question, the current `ScrollView` implementation at React Native's core doesn't allow customizing the duration of the `scrollTo` animation, which is unfortunate. It might evolve later, but for now we're stuck with the default one (and it's quite brutal, I agree with you).

**Comment by bd-arc** [comment]
The issue should be solved if you use the following commit:
```
"react-native-snap-carousel": "https://github.com/archriss/react-native-snap-carousel#1f91a32"
```

Can you confirm?

**Comment by bd-arc** [comment]
Version `3.3.1` should solve the issue ;-)

**Comment by kozillla** [comment]
@bd-arc 
Yes that was happening only on Android.  Thanks for fixing this up. All good now :-)
