### ISSUE TITLE
Is there any option to hide carousel ?

### ISSUE THREAD

**Issue by emregurler** [archriss/react-native-snap-carousel#175]
I want to hide carousel when screen opens. After pressed a button or smth, I want to set it visible. However, I didnt find that prop, how can I do that

**Comment by bd-arc** [comment]
Hi @emregurler,

There is no need for that since you can use the layout prop `display` and set it to either `flex` or `none` (see [RN doc](https://facebook.github.io/react-native/docs/layout-props.html#display)). However, from a performance standpoint, I would recommend rendering it only when needed.
