### ISSUE TITLE
How to make active screen in center

### ISSUE THREAD

**Issue by leogeng** [archriss/react-native-snap-carousel#186]
Implement as the following:
```
imgs: {
    width: 600,
    height: 330,
  
  },
  playlistItem: {
    width: 500,
    height: 330,
    fontSize: 50,
  },

<View style={styles.content}>
        <Image source={require("../resource/left.png")} />
        <Carousel
          data={this.state.playlistItems}
          renderItem={item => this._renderContentItem(item.item)}
          sliderWidth={500}
          itemWidth={500}
          firstItem={0}
          containerCustomStyle={styles.imgs}
          enableMomentum={false}
          loop
          loopClonesPerSide={2}
          autoplay
          autoplayDelay={500}
          autoplayInterval={3000}
          activeSlideAlignment="center"
        />

        <Image source={require("../resource/right.png")} />
      </View>

_renderContentItem(item: GSMaterial) {
    return <Text style={styles.playlistItem}>{item.id}</Text>;
  }
```

and get the following result:
![image](https://user-images.githubusercontent.com/3293583/31645454-b9ad4c62-b2c1-11e7-86d8-953b4a46842a.png)

Even if scroll to the fourth element, the active element is also on the left.
How to make the active element in the center?

**Comment by bd-arc** [comment]
Hi @leogeng,

`itemWidth`'s value should always be less than `sliderWidth`'s one, otherwise no space remains to display the previews on both side. Also, note that the width you've defined in `styles.imgs` will be overridden by `sliderWidth` (see the relevant [source code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L970:L977)).

I recommend getting rid of `width: 600` in `styles.imgs` and setting `sliderWidth` to `600`. Everything should then work properly.

**Comment by leogeng** [comment]
Thank you  @bd-arc ,it works
