### ISSUE TITLE
Flatlist props "inverted" not supported

### ISSUE THREAD

**Issue by gitlovenotwar** [archriss/react-native-snap-carousel#197]
Flatlist has inverted props which it starts from the right. Please add support on it. Thank you. Great work!

**Comment by bd-arc** [comment]
Hi @gitlovenotwar,

If you take a look at [the source code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L1023), you'll see that the prop has already been implemented. But you don't have the liberty to override it because it is used to provide RTL support (by hacking around a tedious RN issue).

What would be your use case?

**Comment by gitlovenotwar** [comment]
Hi, my items should suppose to start at the end.

**Comment by bd-arc** [comment]
Well, I'll expose the prop in the next release. But be aware that overriding it will mess with RTL devices.

**Comment by bd-arc** [comment]
Done in version `3.4.0` ;-)

**Comment by bradleat** [comment]
Please include this in the documentation.
