### ISSUE TITLE
I admit I'm too stupid to install and run an example

### ISSUE THREAD

**Issue by neilyoung** [archriss/react-native-snap-carousel#205]
Not a rant, just a fact. It's me

**Comment by neilyoung** [comment]
import Carousel from 'react-native-snap-carousel';

export class MyCarousel extends Component {

    _renderItem ({item, index}) {
        return (
            <View style={styles.slide}>
                <Text style={styles.title}>{ item.title }</Text>
            </View>
        );
    }

    render () {
        return (
            <Carousel
              ref={(c) => { this._carousel = c; }}
              data={this.state.entries}
              renderItem={this._renderItem}
              sliderWidth={sliderWidth}
              itemWidth={itemWidth}
            />
        );
    }
}


<img width="457" alt="iphone_8_plus_-_ios_11_1" src="https://user-images.githubusercontent.com/731020/32364770-20d3fa9a-c077-11e7-8aa6-21985f2cad09.png">

**Comment by bd-arc** [comment]
@neilyoung I don't know what you do expect from this issue, but:
- **you did not respect [the contribution guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)**
- **you did not try or analyze [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)**
- **the error has nothing to do with the plugin** and is pretty straighforward: you didn't provide anything valid to the `data` prop since you didn't store anything in `this.state`.

Take a look at the example's [source code](https://github.com/archriss/react-native-snap-carousel/tree/master/example/src) and at [its doc](https://github.com/archriss/react-native-snap-carousel/blob/master/example/README.md) if you have trouble running it.

**Comment by neilyoung** [comment]
Well, tried to clone your repo first, did "npm install", opened the example project and was unable to compile the iOS version. However, no issue. Will use something else. Don't have the time to mess with other's issues

**Comment by bd-arc** [comment]
Well, do as you wish of course. Just note that we've devoted countless hours creating and maintaining this plugin, and even more helping other (as proved by the fact that you've been answered in less than 30 minutes).

I'm curious about what would happen if we, and every Open Source contributor, were to say *"Don't have the time to mess with other's issues"* to people asking for help...

**Comment by neilyoung** [comment]
You're so right. And now rest in peace....

**Comment by tomtomgo92** [comment]
@neilyoung i ask the same question this is the answer
https://stackoverflow.com/questions/51944706/cant-use-react-native-snap-carousel

As the screenshot says it, this.state.entries is null.

You must initialize it :

```
export default class App extends React.Component {
  constructor() {
    super()
    this.state = {
      entries: [],
    }
  }
  _renderItem ({item, index}) {
    return (
      <View style={styles.slide}>
          <Text style={styles.title}>{ item.title }</Text>
      </View>
  );}

  render () {
    return (
      <Carousel
        ref={(c) => { this._carousel = c; }}
        data={this.state.entries}
        renderItem={this._renderItem}
        sliderWidth={150}
        itemWidth={100}
      />
 ); 
}}
```
In this exemple, entries: [] wont display anything since there's no object in it. You can initialize with wanted data:

```
entries: [
  { title: 'hello' },
  { title: 'world' },
]
```
