### ISSUE TITLE
why slideStyle is number?

### ISSUE THREAD

**Issue by pesakitan22** [archriss/react-native-snap-carousel#21]
i mean, should it be stylesheet?

**Comment by Exilz** [comment]
Actually, if you log an import of a stylesheet, you'll find a number. I guess it's a reference used by React-native. Since you could also pass an object, it should be `PropTypes.oneOfType([PropTypes.number, PropTypes.object])` or `View.propTypes.style`, yes.
I'll update it in the next minor release.
