### ISSUE TITLE
Modifying Animation Speed

### ISSUE THREAD

**Issue by gonzalezchris** [archriss/react-native-snap-carousel#213]
### Is this a bug report or a feature request?

This is a question

First off thanks for creating react-native-snap-carousel! It's been very helpful!

Do you have any tips on how I would go about modifying the swiping speed or animation? When a user swipes their finger from right to left, to view the next item, the animation seems to ease out, or slow down right before the animation ends. I'd like to change it so that the animation speed is linear and consistent throughout the life of the animation.

Thanks in advance! 

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel#reporting-an-issue) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

This is not a bug, but is a question regarding the animation speed when swiping through items

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

(Write your answer here.)

### Environment

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by bd-arc** [comment]
Hi @gonzalezchris,

Unfortunately, the `ScrollView` upon which the plugin is ultimately based [doesn't offer any kind of animation speed option](https://github.com/archriss/react-native-snap-carousel/#flatlist-and-scrollviews-limitations).

Two currently opened issues might interested you though:
- #189: in which I've explained the problem and talked about incoming attempts to implement `pagingEnabled` and `snapToInterval` in order to smooth things out on iOS.
- #203: in which I've listed React Native's Canny issues on which everyone can vote to put the focus on the most needed evolutions ;-)
