### ISSUE TITLE
Crashes on iOS device (not sim) when an animated gif is used

### ISSUE THREAD

**Issue by gabrielbull** [archriss/react-native-snap-carousel#218]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel#reporting-an-issue) regarding bug report?

No

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

iOS, on device only, not on simulator

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

Yes

### Environment

  Environment:
    React: 16.0.0-beta.5
    React native: 0.49.2
    react-native-snap-carousel: 3.3.4

  Target Platform:
    iOS (10.3)

### Steps to Reproduce

1. Include animated gif as an <Imaged/> component inside the carousel

### Expected Behavior

No crash 

### Actual Behavior

Crash

### Reproducible Demo

None, just include a gif in the carousel and run on device.

**Comment by bd-arc** [comment]
Hi @gabrielbull,

This looks like a React Native bug. I see no reason why the plugin would create a particular error since the component is basically a `FlatList`...

Two things:
- Can you share the app's stack trace when the crash occurs?
- Can you create a simple `FlatList` and see if you also have the issue? Note that you can reuse the same props `data` and `renderItem`, as well as the same styles.

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
