### ISSUE TITLE
Scroll is always stopped on left item

### ISSUE THREAD

**Issue by ziks21** [archriss/react-native-snap-carousel#233]
Hello. Thank you for this great package

I'm trying to implement carousel like this:
<img width="124" alt="screen shot 2017-12-21 at 7 15 25 pm" src="https://user-images.githubusercontent.com/5039404/34266845-592bae42-e683-11e7-8537-20f302542b3b.png">
But i faced with a problem that when i drag scroll by gestures and release touch - it always go to left item of current chosen. Like this:
Moment of touch release (same behavior even if stop touch righter):
<img width="154" alt="screen shot 2017-12-21 at 7 17 50 pm" src="https://user-images.githubusercontent.com/5039404/34266958-c9fbf7c6-e683-11e7-803f-3a6b1c5639a6.png">
Result:
<img width="124" alt="screen shot 2017-12-21 at 7 15 25 pm" src="https://user-images.githubusercontent.com/5039404/34266977-d7daa5c2-e683-11e7-8ad8-4909e6b0dcf9.png">

Here is my code:
```
renderItem({item, index}) {
        return (
            <View style={{width: 30, height: 60, alignItems: 'center', justifyContent: 'center', backgroundColor: 'red'}}/>
        );
    }

...

<Carousel
     ref={(c) => { this.carousel = c; }}
     data={this.items}
     renderItem={this.renderItem.bind(this)}
     sliderWidth={90}
     itemWidth={30}
     activeSlideAlignment={'center'}
     enableSnap={true}
     firstItem={ 1 }
     lockScrollWhileSnapping={true}
     inactiveSlideScale={0.67}
     enableMomentum={true}
     onScrollEndDrag={this.onScrollEndDrag.bind(this)}
/>
```

Could you point me how to fix that or what i'm doing wrong please?
Thanks

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

Since your items have a really small width, you will have to decrease the default value of [`activeSlideOffset`](https://github.com/archriss/react-native-snap-carousel/#behavior) accordingly. You might also want to reduce the value of props `swipeThreshold` and `callbackOffsetMargin`.

Note that this plugin wasn't created with slides that small in mind, since it is questionable from a usability point of view.
