### ISSUE TITLE
"Scroll back to first child when end reached" behaviour for autoplay not working

### ISSUE THREAD

**Issue by carsonwah** [archriss/react-native-snap-carousel#243]
### Is this a bug report or a feature request?

Bug report.

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes.

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes.

### Have you made sure that your issue hasn't already been reported/solved?

Yes.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both.

### Is the bug reproductible in a production environment (not a debug one)?

Yes.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

Yes.

### Environment

  Environment:
    React: 16.0.0
    React native: 0.51
    react-native-snap-carousel: 3.5.0

  Target Platform:
    Android (6.0)
    iOS (11.2)

### Steps to Reproduce

Refer to minimal example below.

### Expected Behavior

Autoplay should be able to play back to the start, or at least has a way to accomplish this.

### Actual Behavior

Autoplay does not play back to the start.

### Reproducible Demo

https://snack.expo.io/H1B93RDNG

---

### Remarks

I just upgraded from 2.4.0 to 3.5.0. It works fine (will scroll back to start) when I was under almost the same setting (except that I need to migrate to data+renderItem combo). Is there any API changes I missed or it really is a bug?

**Comment by bd-arc** [comment]
Hi @carsonwah,

Indeed, the default behavior has changed since version `3.3.0` and the addition of the "infinite loop" feature.

If you set `loop` to `true`, the carousel will seamlessly continue autoplaying when reaching the end of the set, while if you set it to `false`, the carousel will stop autoplaying after reaching the last slide.

This prevents the old ugly effect where you would see the carousel scroll back to the first item. Hope that makes sense ;-)

**Comment by carsonwah** [comment]
@bd-arc Thanks for the timely reply. The infinite loop feature seems cool. Will definitely check it out.
