### ISSUE TITLE
Custom animations

### ISSUE THREAD

**Issue by iremlopsum** [archriss/react-native-snap-carousel#244]
I didn't entirely understand from the documentation, is it possible to have custom animations while swiping? For example if I want to animate translateX instead of scale or opacity to create a "dragging behind" effect.

Is that something that's currently possible?

**Comment by bd-arc** [comment]
Hi @iremlopsum,

Unfortunately, what you're after is not currently possible. The custom animation options you can provide will still be used to animate the opacity and/or the scale of the items as soon as they become active (e.g. when you've scrolled past the center of the next/previous item). You can try [the example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) if you want to see how it works.

I would really like to implement the kind of animation you describe, but this would require being able to interpolate the scroll position and a custom animation at the same time. This, as far as I know, is not currently possible with the `Animated` API. We had a recent discussion about that in #226.

I'll try to see what happens if we were to animate the `translateX` property of the items while scrolling. I don't think that this is going to be smooth though...

**Comment by bd-arc** [comment]
Hi @iremlopsum,

I've tried different setups and this is the closest I was able to come up with:

![react-native-snap-carousel custom animations](https://i.imgur.com/C7d09qs.gif)
```
outputRange: [0, 1, 1]

{
    translateX: animatedValue.opacity.interpolate({
        inputRange: [0, 1],
        outputRange: [-200, 0]
    })
}
```

Another possible effect:

![react-native-snap-carousel custom animations](https://i.imgur.com/7shpgNB.gif)
```
outputRange: [0, 1, 0]

{
    translateX: animatedValue.opacity.interpolate({
        inputRange: [0, 1],
        outputRange: [550, 0]
    })
}
```

If this is something that users find useful, I can add the ability to provide a custom interpolator.

**Comment by bd-arc** [comment]
Feature released in [version `3.6.0`](https://github.com/archriss/react-native-snap-carousel/releases/tag/v3.6.0).

**Comment by diegorodriguesvieira** [comment]
@bd-arc please can you help me as I would animate the background color?

**Comment by bd-arc** [comment]
@diegorodriguesvieira That would be a problem since you can't use the native driver to animate colors: https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated#caveats

And the scroll interpolation is native-powered...
