### ISSUE TITLE
no such file or directory  ..\node_modules\encoding\node_modules\iconv-lite

### ISSUE THREAD

**Issue by anvesh523** [archriss/react-native-snap-carousel#248]
While I'm running 'npm install' command, I'm facing below error. Please give some suggestions.

npm ERR! path D:\WorkSpace\react-native-snap-carousel\node_modules\encoding\node_modules\iconv-lite
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\WorkSpace\react-native-snap-carousel\node_modules\encoding\node_modules\iconv-lite' -> 'D:\WorkSpace\react-native-snap-carousel\node_modules\encoding\node_modules\.iconv-lite.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nltuser2\AppData\Roaming\npm-cache\_logs\2018-01-19T08_08_41_511Z-debug.log

[2018-01-19T08_08_41_511Z-debug.log](https://github.com/archriss/react-native-snap-carousel/files/1645718/2018-01-19T08_08_41_511Z-debug.log)

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

Clearly, your issue has nothing to do with the plugin but rather with a `npm` mismatch.

Since I'm in a good mood, I've got two links for you:
- https://github.com/npm/npm/issues/17444#issuecomment-321851320 -> for a probable solution
- http://bfy.tw/G86m -> for your next issues

**Comment by anvesh523** [comment]
Thanks for the help.
