### ISSUE TITLE
[Help wanted] How to achieve below UI?

### ISSUE THREAD

**Issue by SanyasiraoM** [archriss/react-native-snap-carousel#259]
### Is this a bug report or a feature request?

Help wanted

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

(Write your answer here.)

### Environment

  Environment:
    React: 16.0.0-alpha.12
    React native: 0.48.4
    react-native-snap-carousel: 3.5.0

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

![sffkgbfmkbmnm2xeypzadhg](https://user-images.githubusercontent.com/8909624/35670592-f981d1e0-075e-11e8-990e-60d18754c6a3.png)

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior
The center card is being pushed to right side, become not visible if we scroll more cards

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by bd-arc** [comment]
This is pretty straightforward.

Use [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) as a starting point and simply change [line `13` of `SliderEntry.style.js`](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/styles/SliderEntry.style.js#L13) to:
```
const slideWidth = wp(30);
```

Done!

![react-native-snap-carousel issue 259](https://i.imgur.com/mU7EZJrm.png)

⚠️ Since your items will have a small width, you may want to decrease the default value of [`activeSlideOffset`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior) accordingly. You might also need to decrease the values of props `swipeThreshold` and `callbackOffsetMargin`.

**Comment by SanyasiraoM** [comment]
@bd-arc Thanks for reply,

Here left and right cards not completely visible, because of slider width

How to reduce margins between items after applied scaling or how to remove space added by scaling.

**Comment by bd-arc** [comment]
You need to read [the doc](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in depth in order to understand how the plugin works.

[Here is](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#margin-between-slides) a note about margin and [here is](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#understanding-styles) a screenshot that illustrates how `itemWidth` and `sliderWidth` work together.
