### ISSUE TITLE
Does it render all items at once?

### ISSUE THREAD

**Issue by grundmanise** [archriss/react-native-snap-carousel#26]
Hi,
does this component render all items at once or only visible items are rendered?
does it support `removeClippedSubviews` prop of `ScrollView`?

**Comment by bd-arc** [comment]
@grundmanise Hi! For now, all items are rendered at once. But we are currently working on implementing a `preload` prop that will allow rendering only the current item as well as a specific number of the previous and next ones. Stay tuned!

As for your other question, and as [stated in our README](https://github.com/archriss/react-native-snap-carousel#props), you can use any prop from the original ScrollView component. Actually, we totally recommend activating it when your scroller doesn't need to handle too many items since this really enhances scroller's performance.

**Comment by grundmanise** [comment]
p.s. maybe this would help you https://github.com/sghiassy/react-native-sglistview :)

**Comment by cinder92** [comment]
any update about this?

**Comment by bd-arc** [comment]
Hey @cinder92,
Yes, I confirm that we are still working on it. It's taking some time though, because this requires a lot of refactoring and miscellaneous solutions are tested. FYI, we are currently considering using the new `<FlatList />` component.

**Comment by fendorio** [comment]
Hey there, nice repo - I've just been checking it out on IOS. 

Quick question for anyone a bit more knowledgable on this project. 

In the meantime, is the workaround for this to watch the current index of the slide and utilise some AJAX logic to go fetch more items / populate the carousel with more items which are stored in the apps memory but just not rendered yet?

Hope that makes sense

**Comment by bd-arc** [comment]
@fendorio Yes, you could totally do that to provide some sort of infinite scroll. You can use `onSnapToItem` to check if you've reached the last slide, fetch some more items and update your state.

Note that we haven't tested this use case yet, but since our plugin supports dynamic slides, you should be able to easily implement it.

**Comment by PublicParadise** [comment]
@bd-arc: I do like `react-native-snap-carousel`. But unfortunately I can't use it. It just breaks down at around 2000 items. Render time balloons to 10s. Would you guys be interested in creating an experimental branch exploring that `<FlatList/>` idea? That's the only way to solve my performance problem with the current version of `react-native-snap-carousel`. I'd be willing to chip in and push PRs if needed.

Thanks for considering!

**Comment by bd-arc** [comment]
Hi @PublicParadise,
I understand your concern but, as stated [here](https://github.com/archriss/react-native-snap-carousel/issues/73#issuecomment-303090987), `<FlatList />` is shipped with bugs that are really problematic for our most common use cases.

To be honest, we've never thought that it would be used to display that many items. May I ask you to provide a bit more context?

Still, we're open to go with your suggestion and experiment on a dedicating branch. I'll push my own developments as soon as I have something stable ;-)

**Comment by PublicParadise** [comment]
Hi @bd-arc,  

my use case is a real estate app that shows pictures of properties - similar to what [Trulia](https://www.trulia.com/mobile/) does. Another use case would a simple photo album. In these days 2000 photos is nothing!

This is an interesting topic. Let me mover over to https://github.com/archriss/react-native-snap-carousel/issues/73. That seems to be the right place for this discussion.

**Comment by bd-arc** [comment]
Hi guys,

Great news: the `FlatList` implementation is finally here for you to try!

Take a look at [the `flatlist` branch](https://github.com/archriss/react-native-snap-carousel/tree/flatlist) that features a `Carousel` more performant than ever, an updated README and an updated example.

I'm closing this issue since it's better if the follow-up discussion takes place in #73. Make sure to let me know what you think ;-)

**Comment by alirehmanappcrates** [comment]
Hi everyone,
I have 20 items on my list but when I tried to console I'm getting this, I need to render all at once.

![Screenshot 2021-11-23 at 1 27 10 PM](https://user-images.githubusercontent.com/86340695/142991159-c654b59f-3072-4971-a588-4d149dcfe7ba.png)
