### ISSUE TITLE
Proposal of channel discussion

### ISSUE THREAD

**Issue by MichelDiz** [archriss/react-native-snap-carousel#266]
Hi, I took the liberty of creating a public chat in the discord facing React-Native. With the intention of uniting the React-native community and improving communication.

I'm creating a channel for public discussions about your project. To avoid flooding "chat" on your github. If you can support the initiative, great! Just share the link below xD

I'm adding RN-only projects to this public chat service. And I commit myself to manage rooms.

here's the link
https://discord.gg/RvFM97v

Cheers.

**Comment by bd-arc** [comment]
Hey @MichelDiz, thanks for the initiative!

Unfortunately, I'm not a Discord user myself and don't intend to become one at the moment. Still, I'm going [to tag this thread with an asterisk](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#useful-threads) so that users who are interested can find it ;-)
