### ISSUE TITLE
Vertical corousel not working properly

### ISSUE THREAD

**Issue by nakulkundaliya** [archriss/react-native-snap-carousel#272]
I am trying to implement vertical corousel but facing issue with 3rd component, http://prntscr.com/ii58si 
I want center one to be on the top and 1st and 3rd elements should go behind the focused one.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**The carousel is working properly. To achieve what you're after, you need to implement a custom interpolation. I've written [an entire guide](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md) dedicated to this advanced feature.**

**You'll have to use the following trick to render the active item on top of the others:**
```
{ zIndex: carouselProps.data.length - index }
```

**But beware, due to a React Native bug, it just doesn't work on Android! See [this](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md#android) for more info.**
