### ISSUE TITLE
Examples 5-8 do not work on Android

### ISSUE THREAD

**Issue by LukasNavickas** [archriss/react-native-snap-carousel#278]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Sure

### Have you made sure that your issue hasn't already been reported/solved?

Prety sure

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

Yes!

### Steps to Reproduce

0. Install the required invornment and launch examples
1. Examples 5-8 (from (https://github.com/archriss/react-native-snap-carousel/tree/master/example) ) do not work. They are not shown at all (the lists ends with the example 4. on Android). 
2. No logs are provided after executing "react-native log-android".

### Expected Behavior

Examples 5-8 should work on Android

### Actual Behavior

Examples 5-8 do not work on Android, not shown on the screen

### Reproducible Demo

Just check your repo's example folder and try to launch it with my settings.

**Comment by bd-arc** [comment]
@LukasNavickas Yes, that's on purpose.

If you read [the source code](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L138) and [this note](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md#android) you'll understand why. To be honest, I went the easy way because I was tired of having to do everything twice thanks to yet another RN bug.

However, in the aforementioned note, I provide 3 workarounds that you can try. The first one should allow you to get it working on Android pretty quickly ;-)

> - Remove the condition `!IS_ANDROID`
> - Add `{ elevation: carouselProps.data.length - index }` in the relevant animated styles

Note that I'll be working on a complete overhaul of the example as soon as I can free up the time required to do so (see #257 for more info).
