### ISSUE TITLE
question: the example is not running smoothly on IOS simulator but pretty good on android simulator.

### ISSUE THREAD

**Issue by leojiang** [archriss/react-native-snap-carousel#293]
I just wanna ask why the example is not running smoothly on IOS, even a simple animation will take several seconds to finish. 

Is there anything I can do to make it better or it's just because of the performance of simulaor?

**Comment by bd-arc** [comment]
There must be something wrong on your end, because the example runs pretty smoothly. Every screencast that you can find in the doc has been taken from it and even with the necessary GIF compression, you can tell that there is no performance issue ([see for yourself](https://github.com/archriss/react-native-snap-carousel#raised_hands-new-feature-layouts)).

My guess is that you've activated the "Slow animations" feature by mistake without noticing it. See https://stackoverflow.com/a/33669398/8412141 for more info.

**Comment by leojiang** [comment]
Thanks, man, I did turned on 'Slow animation'.
