### ISSUE TITLE
Tinder but with like/dislike on swipe

### ISSUE THREAD

**Issue by asadm** [archriss/react-native-snap-carousel#295]
Thank you for making this awesome project!
I am trying to implement the following "tinder-style" swiper:
![tinder](https://axurewidgets.com/wp-content/uploads/2016/11/tinder-swipe.gif)

I see that there is a tinder example. The only problem I have is how do I make it unidirectional? ie. no matter which direction I swipe the current item (yay or nay), it always should go to the next item in the deck. User shouldn't be able to swipe back to previously dismissed item. 
Does this make sense? Is this possible with `slideInterpolatedStyle`?

**Comment by bd-arc** [comment]
Unfortunately no. The reason is that the component is basically a `ScrollView`, which mean we can apply miscellaneous interpolations based on scroll position, but not prevent the user from going back.

You should check the following plugin which does exactly what you're after: https://github.com/alexbrillant/react-native-deck-swiper
