### ISSUE TITLE
Refresh when scrolling to the edge at first/last item

### ISSUE THREAD

**Issue by GillesVercammen** [archriss/react-native-snap-carousel#308]
### Is this a bug report or a feature request?

feature request

Hello,

I'm trying to implement a refresh on swipe mechanic on the carousel but so far i have been unable to make it work. I tried making use of onScroll and onScrollBeginDrag/onScrolEndDrag. But that didn't suffice. Is there another way of implementing a swipe to refresh?

use case: I want my list to call a refresh method whenever the user swipes further than the last/first item in the list

thank you!

**Comment by bd-arc** [comment]
Hi @GillesVercammen,

Have you tried playing with `VirtualizedList`'s [inherited props](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#inherited-props)? Particularly [`onEndReached`](https://facebook.github.io/react-native/docs/virtualizedlist.html#onendreached).

**Comment by GillesVercammen** [comment]
Tnx for the suggestion. I tried it out and it seems super buggy. It sometimes calls onEndReact on the first render of the component. Also It calls onEndReached twice with the bounce from flatlist.
I could make it work. But it is super dirty en fragile. sadly onRefresh en is refreshing props do not work for horizontal list.

**Comment by bd-arc** [comment]
@GillesVercammen Sorry for not getting back to you sooner. Indeed, the `FlatList` component is super buggy in vertical mode and it only gets worse when going horizontal...

I have been facing too many issues with horizontal FlatLists to recommend implementing an infinite scroll feature with it. For now, I would clearly go with a manual refresh button, as per your suggestion.

I'm going to close the issue since there's nothing much we can do about it at the moment. But feel free to continue the discussion and let's hope one of us finally come across a more robust solution ;-)

**Comment by franznkemaka** [comment]
Hi,
My answer might be too late, since i have been facing the same issue, i decided to share with you guys my temporal fix.
This is not the best solution but at least something similar.
use **onSnapToItem** to know whenever the active item changes.
` <Carousel
                data={this.state.users}
                ref={(ref) => { this.carouselRef = ref; }}
                 ...
                onSnapToItem={(index) => {
                    let lastIndex = users.length - 1;
                    if (index === lastIndex) {
                         // do your fetch stuff here :)
                        let newUsers = [];
                        this.setState({ users: newUsers }, () => {
                                 // jump to the previous index
                                this.carouselRef.snapToItem(index, true);
                        });
                    }
                }}
            />`

You can now re-fetch whenever the last item is rendered but  unfortunately the **snapToItem** is not working correctly.
For your own convenience, you can still add a button to refresh manually!
Thanks,
Have fun 👍
