### ISSUE TITLE
How to auto height the carousal's height ? 

### ISSUE THREAD

**Issue by MbF-Sathya** [archriss/react-native-snap-carousel#327]
Hi., 
I have used this carousal like a fixed heighten image like 400 px width and height. so under that i have pagination dots then under that i have content about the image. 

so now what i tried to do is , for example i have 5 slides so each and every slides contains different lines of contents. so here i what the carousal's height should auto height.

Because, i have some other component under the whole carousal. so how it looks if less amount of content will make more space because of the fixed heighten carousal. 

how to solve this?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your question, this is not possible because the plugin is based on the `ScrollView` component which doesn't support dynamic height sizing.**
