### ISSUE TITLE
How to rerender an item?

### ISSUE THREAD

**Issue by jarecsni** [archriss/react-native-snap-carousel#328]
I have some cards with buttons on them. When the buttons pressed the cards need rerendering as the information on them will change according to the button press. How could I trigger this rerender - ideally such that only the impacted card gets rerendere?

Thanks!

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

Regarding your question, and since the `Carousel` component extends the `FlatList` one, you can try to use prop `extraData={this.state}` and see if this solves your issue. You can take a look at the [RN doc](https://facebook.github.io/react-native/docs/flatlist.html#extradata) for more info.

Note that this has already been mentioned in #133 and #180.

**Comment by jarecsni** [comment]
It helped thanks!
