### ISSUE TITLE
vertical implementation

### ISSUE THREAD

**Issue by hugohow** [archriss/react-native-snap-carousel#37]
Hello,

I'm trying to implement it in vertical, and I want it to know if you have any evolutions on this subject ?

Thanks for this great library !

**Comment by bd-arc** [comment]
@hugohow Hi there! As you [might have seen](https://github.com/archriss/react-native-snap-carousel#todo), adding vertical implementation is clearly on our radar.

Unfortunately, we haven't had time to work on this feature yet. If you want to dig in the source code and submit a PR, you're more than welcome ;) Since you've requested it, I'll try to take a look at it in the near future.

**Comment by hugohow** [comment]
Thanks ;) I will try to do it !

**Comment by gajus** [comment]
> Thanks ;) I will try to do it !

@hugohow Are you still continuing with this?

**Comment by bd-arc** [comment]
@hugohow @gajus I'm pleased to let you know that version 2.2.0 introduces vertical support ;-)
