### ISSUE TITLE
Height adds space for non-rendered components

### ISSUE THREAD

**Issue by reinvanimschoot** [archriss/react-native-snap-carousel#381]
### Is this a bug report, a feature request, or a question?

Question

I am trying to add a Carousel for posts that contain an image and text. The image is required but the text is not. 

However, on slides where there is not text to see, the height is still adjusted for an empty text block, while this is actually a conditionally rendered component. So I end up with too much whitespace on posts with no text. Is there a way to make sure the height is changed dynamically when text does appear?

**Comment by bd-arc** [comment]
@reinvanimschoot Can you please share a [Snack example](https://snack.expo.io/) in order for me to see what you've tried so far?

**Comment by reinvanimschoot** [comment]
@bd-arc I did some more research and I believe this behaviour is inherent to FlatList itself. I am trying to show the Carousel, nested in a vertical FlatList. And in this case, the nested Carousel always takes the hight of the highest item, even when for items that are lower in height.

When I tried this with a pure horizontal FLatList, nested instead of the Carousel, I got the same problem. So I guess it is not related to your package :) which, besides that, works great!

I guess I need to find another way of doing this instead of a nested FlatList.

**Comment by bd-arc** [comment]
@reinvanimschoot Thanks a lot for sharing your findings!

There are so many limitations with `FlatList` that it never takes long before running into frustration :-) I'm currently working on ditching the component myself...

I'm going to close the issue since it's not related to the plugin, but feel free to share more discoveries if you manage to achieve the layout you're after  ;-)
