### ISSUE TITLE
Signaler Screen example

### ISSUE THREAD

**Issue by wesleyguirra** [archriss/react-native-snap-carousel#382]
Hi, I’m trying to do something like the signaler screen on showcase app, it’s a signup walkthrough, could you share some example or tutorial about how can I do it?

**Comment by bd-arc** [comment]
@wesleyguirra There is nothing much to it, really. It's simply a custom component with pages between which you alternate when pressing the prev/next buttons.

Today, I would use something like [this plugin](https://github.com/jfilter/react-native-onboarding-swiper) in order to simply button handling. Combine this with a bit of logic in order to check that all the criteria are met before enabling your "next" button, and you'll be up in no time ;-)

**Comment by wesleyguirra** [comment]
Hey @bd-arc thank you for your time answering my question, I really appreciate your suggestion to use that plugin, I have one more doubt: As what I'm trying to reach is signup screen, I'll have some validations on fields, and I'll need to add new sliders when the field is valid, i.e. I need to add some conditional slides/screens. is this possible, there's a specific plugin for that?

**Comment by bd-arc** [comment]
@wesleyguirra Well, I don't have any particular plugin in mind regarding your use case, but here is what I suggest:
- [tcomb-form-native](https://github.com/gcanti/tcomb-form-native) for form validation
- [JsCoach](https://js.coach/?collection=React+Native) for finding interesting plugins of all sorts.

Hope this helps!

**Comment by wesleyguirra** [comment]
Hey @bd-arc could you share how to do the signaler example of archriss example, I think that  effect is exactly what I'm trying to reach did you use the snap-carousel to achieve that effect?
