### ISSUE TITLE
Problem using dynamic data

### ISSUE THREAD

**Issue by jonathandion** [archriss/react-native-snap-carousel#41]
Hi,

When I use dynamic data I have an error ``` undefined is not an object (evaluating 'this._positions[index].start')``` but when I use static data everything seem to work.

What I'm doing wrong ?

Thanks.

**Comment by bd-arc** [comment]
@jonathandion Hi,
This is probably the same issue as #35. There must be something wrong with component's state management. I'll look into it as soon as possible.

**Comment by jonathandion** [comment]
@bd-arc Hey Benoit,

Thanks sorry for the misunderstood. When I mean dynamic" I mean using data from my server using Ajax. When I use ```this.state.items``` I have that error.

**Comment by bd-arc** [comment]
@jonathandion I'll reproduce my answer to [this issue](https://github.com/archriss/react-native-snap-carousel/issues/31#issuecomment-277313108) :)

My guess is that you're trying to render the carousel while it has no child at all. Am I right? Indeed, this would fail since the component depends on children's length. We need to improve component's state management in order to handle this kind of usage.

For now, I would recommend you to render the carousel conditionally. Something along those lines:

```
get loader () {
    return (
        <ActivityIndicator size={'small'} />
    );
}

get carousel () {
    const { entries } = this.state;
    return (
        <Carousel>
            { entries }
        </Carousel>
    );
}

render () {
    const { products } = this.state;
    return !products.length ? this.loader : this.carousel;
}
```

Does this do the trick for you?

**Comment by jonathandion** [comment]
@bd-arc thanks it's working 👍
