### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by AntoineGrandchamp** [archriss/react-native-snap-carousel#43]
I get this error when I run my tests with jest and it tries to import react-native-snap-carousel :
`
TypeError: Cannot read property 'style' of undefined      
      at Object.<anonymous> (node_modules/react-native-snap-carousel/index.js:472:842)
`

**Comment by stivaugoin** [comment]
Same problem here!

**Comment by bd-arc** [comment]
@AntoineGrandchamp I am not familiar with Jest, but I can investigate in order to see what triggers this error. Can you share your test script?

**Comment by AntoineGrandchamp** [comment]
Here is my test file : 
```
import 'react-native';

import configureStore from 'redux-mock-store';
import { Provider } from 'react-redux';
import React from 'react';
import renderer from 'react-test-renderer';
import { dictionaries } from '../../../i18n/translation';
import Guides from '../Guides';

const reducers = [];
const mockStore = configureStore(reducers);
const store = mockStore({});

const props = {
  navigation: {},
  onSetGuide: () => {},
};

it('renders correctly', () => {
  const tree = renderer.create(
    <Provider store={store}>
      <Guides 
        {...props}
      />
    </Provider>,
  ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

The error pops when `import Carousel from 'react-native-snap-carousel';` is called in the file `Guides.js`.

I did some tests and it seems like `ScrollView.propTypes` at line 44 and 48 of your `index.js`file is undefined when the test is run.

**Comment by RCiesielczuk** [comment]
Hi @bd-arc, I've ran into the same issue as @AntoineGrandchamp. Did you manage to have a look at it?

Thanks

**Comment by thurt** [comment]
hi guys,

ran into this problem as well. 

i think the problem is related to these three lines
https://github.com/archriss/react-native-snap-carousel/blob/master/index.js#L56
https://github.com/archriss/react-native-snap-carousel/blob/master/index.js#L60
https://github.com/archriss/react-native-snap-carousel/blob/master/index.js#L87

if I temporarily comment those lines out in `node_modules/react-native-snap-carousel` then jest test no longer gets the described error.

these lines appear to reference this in `react-native` source -> https://github.com/facebook/react-native/blob/v0.43.1/Libraries/Components/ScrollView/ScrollView.js#L297

a temporary solution is to create a mock `react-native-snap-carousel.js` inside a `__mocks__` folder. mine just looks like:
```javascript
/*
  FIXME: using an empty mock in order to bypass jest test error. see tracking issue: https://github.com/archriss/react-native-snap-carousel/issues/43
 */
module.exports = () => {};
```

**Comment by bd-arc** [comment]
Hi guys,

First, kudos to @thurt for your thorough investigation and your temporary solution :)

To be honest, I couldn't find time to play with Jest and try to understand the root of the issue; sorry about that. Still, I really don't get why declaring style proptypes this way would result in `ScrollView` being `undefined`...

I guess I could fall back to something along those lines: `PropTypes.oneOfType([PropTypes.number, PropTypes.object])`. But this is not really elegant...

[This plugin](https://github.com/jaysoo/react-native-parallax-scroll-view) uses the same syntax as ours; does it trigger the same error for you guys?

**Comment by hoangnm** [comment]
It's because React Native does mock ScrollView for you when you write unit test with Jest https://github.com/facebook/react-native/blob/master/jest/setup.js. You can use jest.unmock('ScrollView') before a test file.

**Comment by bd-arc** [comment]
Thanks @hoangnm for this very useful info! I've added it to the [README](https://github.com/archriss/react-native-snap-carousel/#error-with-jest) ;-)

**Comment by bhagwanshelke20** [comment]
Hi 
can any one help to solve this problem . I given code here please help
**Error: **Uncaught TypeError: Cannot read property 'style' of undefined at carousel**

<script type="text/javascript">
			var myIndex = 0;
			carousel();

			function carousel() {
			    var i;
			    var x = document.getElementsByClassName("mySlides");
			    for (i = 0; i < x.length; i++) {
			      x[i].style.display = "none";  
			    }
			    myIndex++;
			    if (myIndex > x.length) {myIndex = 1}    
			    x[myIndex-1].style.display = "block";  
			    setTimeout(carousel, 2000);    
			}
		</script>**

**Comment by Bimpong** [comment]
hi @bshelke ...i actually have your same problem right now... any chance you found a fix you could share?

**Comment by nicolas-amabile** [comment]
I recently had a similar issue while running some tests
<img width="1536" alt="Screen Shot 2020-02-28 at 19 32 01" src="https://user-images.githubusercontent.com/8633440/75592541-50ac0600-5a61-11ea-936b-c38efcbe5acf.png">

Since I need to make assertions on each carousel item, I implemented this simple mock:
```
// __mocks__/react-native-snap-carousel/index.js
const Carousel = ({ data, renderItem }) => data.map((item) => renderItem({ item }));
export default Carousel;
```
