### ISSUE TITLE
Is there a way to disable the border shadow?

### ISSUE THREAD

**Issue by joshuakoh7** [archriss/react-native-snap-carousel#539]
Trying make the carousel stack float over a page but I can't figure out how to disable the border around the carousel item. I've managed to set the container background to transparent but there is still a shadowy border around the parent.

What I've tried:
```
          contentContainerCustomStyle={{opacity: 1, backgroundColor: Colors.transparent, shadowOpacity: 0}}
          containerCustomStyle={{opacity: 1, backgroundColor: Colors.transparent, shadowOpacity: 0}}
```

**Comment by bd-arc** [comment]
@Jonarod I assume you're talking about the example since there is no built-in shadow style in the carousel component itself.

The shadow component is rendered [here](https://github.com/archriss/react-native-snap-carousel/blob/6de6701772069329078d83bf15ce26b35388ec44/example/src/components/SliderEntry.js#L55). You can either modify [its styles](https://github.com/archriss/react-native-snap-carousel/blob/6de6701772069329078d83bf15ce26b35388ec44/example/src/styles/SliderEntry.style.js#L28-L39) or delete it altogether.

**Comment by Jonarod** [comment]
??
