### ISSUE TITLE
contentContainerStyle - padding

### ISSUE THREAD

**Issue by skeie** [archriss/react-native-snap-carousel#56]
Hi,

First off, thanks for this package. It's amazing 🖖.

I was wondering something, is there a special reason why 
`{ paddingHorizontal: containerSideMargin }` is added to `contentContainerStyle` as an own object in an array, instead of doing something like this

```javasciprt

 const contentContainerStyle = {
            ....Stylesheet.flatten(contentContainerCustomStyle || {})
            { paddingHorizontal: containerSideMargin }
        }
// if flatten is to costly, one could change the contentContainerCustomStyle prop from a style to an object
```
The reason I am asking is because I would like to overwrite the paddingHorizontal property
![image](https://cloud.githubusercontent.com/assets/1346122/24831926/9b712114-1ca4-11e7-903f-64531ec10a73.png)

Is this something you guys would accept an PR for?

src: https://github.com/archriss/react-native-snap-carousel/blob/master/index.js#L505

**Comment by bd-arc** [comment]
Hi there!

`paddingHorizontal` has precedence over any other style because it's a critical value responsible for slide's centering. Overriding it would mess with slider's layout.

Could you describe your use case and the reason why you need to change inner horizontal padding? Is there no way for you to deal with it at slide's level?

Regarding you other question, we declare styles that way because it is simpler, [better optimized](https://facebook.github.io/react-native/docs/stylesheet.html#flatten), and transparent for the user ;-) Are you aware of any particular benefit of using `Stylesheet.flatten()` over a simple array?

**Comment by skeie** [comment]
Aha, thanks for the clarification :-). 

So what I would like to do is to center the first element of the slider: 
![image](https://cloud.githubusercontent.com/assets/1346122/24835940/60daf08c-1d0f-11e7-8943-6b38e1f35aa7.png)

like this:
![image](https://cloud.githubusercontent.com/assets/1346122/24835934/39b4721c-1d0f-11e7-88f5-bc6206369016.png)

Here you can see the padding, I don't know how to solve it without using position: 'absolute' or something, maybe you know a better way? :-)
![image](https://cloud.githubusercontent.com/assets/1346122/24835947/91b36022-1d0f-11e7-9cef-d6c6c995b6ca.png)

The styles question. I totally agree why you do it that way, I did not know that you needed the `paddingHorizontal` for the slide centering, so you can disregard that suggestion 😎

**Comment by bd-arc** [comment]
@skeie Thanks for the screenshots! I totally get what you're trying to achieve (in fact, an issue has already been opened for this a few months ago; see #3).

Implementing it is a bit complicated because all of our calculations are based on slider's center (usually viewport's center). It would require some heavy tweaking to achieve the behavior you're after. Since it has been asked multiple times, I'll take a look at it as soon as I can. Unfortunately, it might not be before a few weeks..

For now, could you try locally to move the `paddingHorizontal` rule one line up and override it according to your will? If you manage to achieve something usable, I'll expose it as a prop temporarily ;-)

**Comment by skeie** [comment]
Thanks for the detailed feedback. I understand that this could be tricky... I tried changing to a 'random' number. And I don't have any issue with scrolling for my use case at least. 

If you don't have time to fix it, I made a suggestion [here :-)](https://github.com/archriss/react-native-snap-carousel/pull/58)

Keep up the good work, this library is amazing 🖖

**Comment by bd-arc** [comment]
Closing as prop `carouselHorizontalPadding` [was introduced in 2.1.2](https://github.com/archriss/react-native-snap-carousel/blob/master/CHANGELOG.md).
This prop will remain as long as #3 isn't figured out.
