### ISSUE TITLE
Disable stretch height on Carousel Container

### ISSUE THREAD

**Issue by ariona** [archriss/react-native-snap-carousel#57]
Hello,

I am having a problem here, current carousel height is stretched. If i inspect there is a view that having flex:1. I have tried to set containerCustomStyle, contentContainerCustomStyle, slideStyle flex to 0 but the carousel still stretching the height.

```js
<View style={{flex:1,justifyContent:'center',alignItems:'center'}}>
  <View>
    <Carousel
      sliderWidth={width}
      itemWidth={width-70}
      showsHorizontalScrollIndicator={false}

      containerCustomStyle={{flex:0}}
      contentContainerCustomStyle={{flex:0,alignItems:'flex-start'}}
      slideStyle={{flex:0}}
      onSnapToItem={this.activeSlide}>

      {items}
    </Carousel>
  </View>
</View>
```

![screenshot_20170412-173449](https://cloud.githubusercontent.com/assets/752483/24953761/bc233136-1fa6-11e7-82e5-c99529699862.png)

**Comment by bd-arc** [comment]
Hi,

Well, I don't think that your issue has to do with the plugin since there is not a single `flex: 1` in its source code ;)

I can't help but notice that, in the sample code you provided, the first container is being stretched. Could it be the cause of your issue? Also, is the height of your slides fixed?

**Comment by bd-arc** [comment]
@ariona After giving this a second thought, I realized that I've made a mistake: our `<Carousel />` is basically a `<ScrollView />` and, as such, inherits from [its default styles](https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L746), especially `flexGrow: 1`.

You should be able to deal with it thanks to the prop `containerCustomStyle`. I know you've tried `flex: 0`, but can you give `flexGrow: 0` a try? If this doesn't work, you should either use this prop to pass a custom height to the container or wrap the carousel in a `<View />` with fixed height.

**Comment by ariona** [comment]
Thanks for giving this issue another look :) , It's working now. by setting the flexGrow:0 to containerCustomStyle.

I was using fixed height for workaround but it's bad for dynamic content height.

**Comment by mostafa** [comment]
Would you mind mentioning this in documentation!

**Comment by bd-arc** [comment]
@mostafa No problem :-) I'll add the following to the documentation as soon as I'm finished with the update I'm currently working on.

---

### Carousel's stretched height

Since `<Carousel />` is, ultimately, based on `<ScrollView />`, it inherits [its default styles](https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L864) and particularly `{ flexGrow: 1 }`. This means that, by default, **the carousel container will stretch to fill all the available space**.

If this is not what you're after, you can prevent this behavior by passing `{ flexGrow: 0 }` to the prop `containerCustomStyle`.

Alternatively, you can either use this prop to pass a custom height to the container, or wrap the carousel in a `<View />` with a fixed height.

**Comment by clarissarnr** [comment]
Hi is it possible to remove the flexGrow and flexShrink?

**Comment by clarissarnr** [comment]
Hi, how to remove the default animation?
