### ISSUE TITLE
Handle on swipe 

### ISSUE THREAD

**Issue by Clcll** [archriss/react-native-snap-carousel#85]
Hello
How to handle Swipe(onChange) event.
For example do some action on swipe Left/Right
I saw these methods 
snapToNext (animated = true)
snapToPrev (animated = true)

Thx

**Comment by bd-arc** [comment]
Hi @Clcll,

I'm not sure about what you want to achieve, but I think `onSnapToItem` is the prop you're looking for.

The index of the new slide is passed as an argument to this callback. This means that you can, for example, compare the new index to the previous one in order to determine if you've swiped right or left.

Hope this helps!
