### ISSUE TITLE
Several  slides at a time

### ISSUE THREAD

**Issue by RemyMachado** [archriss/react-native-snap-carousel#865]
### Is it possible to display 3 slides at a time with this carousel and how?
like react-slick is doing:
![image](https://user-images.githubusercontent.com/30229752/131821686-61b83bb6-8876-4bb8-a6ad-bbfa9e74cb6e.png)

**Comment by flexbox** [comment]
@RemyMachado
Yes :)

Here is an example with renderItem
```javascript
	const renderItem = ({ item }) => {
		return (
			<View style={styles.itemContainer}>
				<Text style={styles.itemLabel}>{`Item ${item}`}</Text>
			</View>
		)
	}
```
I just changed the value from the example for the `ITEM_WIDTH` to `0.3`

```javascript
const SLIDER_WIDTH = Dimensions.get('window').width
const ITEM_WIDTH = Math.round(SLIDER_WIDTH * 0.3)
```
Preview

![image](https://user-images.githubusercontent.com/360936/134940341-fcee3eb3-978a-49c2-81d2-ce34dc915814.png)

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
