### ISSUE TITLE
Active slide above others

### ISSUE THREAD

**Issue by pfulop** [archriss/react-native-snap-carousel#89]
Hi is it possible to achieve main slide to be above other ones? Something like this?

![sliders](https://user-images.githubusercontent.com/3984319/27629708-7d6b15ce-5bf3-11e7-8f23-94d76403a401.jpeg)

I tried playing with padding but couldn't get non active slides to be behind main one.

**Comment by bd-arc** [comment]
Hi @pfulop! We've thought about that, but unfortunately it's not possible since the plugin is built on top of the `ScrollView` component.

This could be achieved with a custom `PanResponder` and a lot of head-scratching, but we want to rely on `ScrollView` and `FlatList`'s optimizations. Therefore, we won't be able to provide this kind of layout.

[This nice but no longer maintained plugin](https://github.com/lelandrichardson/react-native-pan-controller) implements a custom `PanResponder` and offers a coverflow effect that can get you started if you feel like creating your own component ;-)

**Comment by pfulop** [comment]
@bd-arc Thank you anyway, btw great job with this carousel :+1: .

**Comment by bd-arc** [comment]
Hi @pfulop,

I think that you're going to be really interested in [my recent findings](https://github.com/archriss/react-native-snap-carousel/issues/195#issuecomment-359746362) ;-)

![react-native-snap-carousel custom animations](https://i.imgur.com/Ta3xHCn.gif)

I'm currently working on allowing users to specify a custom interpolator with which you'll be able to create the kind of layout you were after.

**Comment by pfulop** [comment]
hi @bd-arc 

That looks nice but I already did my own (it was easier than I thought). Definitely keeping this one in repertoire.

**Comment by bd-arc** [comment]
Is your component Open Source by any chance? I'm always interested in taking a look at the solutions others have came up with ;-)

**Comment by pfulop** [comment]
No, altho for the past couple of months I am trying to find some time to make it opensource (at least in article form with example repository).

I should travel tomorrow so maybe I will find some time to get it together ;)

**Comment by bd-arc** [comment]
Do not hesitate to keep me posted ;-)
